language: php
sudo: false
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "nightly"
    - php: "hhvm"
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "nightly"
    - php: "hhvm"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --no-interaction --prefer-dist
  - composer require --dev phpunit/phpunit

script:
  - phpunit --version
  - phpunit --verbose

# vim:ts=2:sw=2:et
